name: bloc_devtools_extension
description: "A flutter devtools extension for flutter_bloc"

version: 1.0.0+1
environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  colored_json: ^1.1.2
  cupertino_icons: ^1.0.8
  devtools_app_shared: ^0.3.1
  devtools_extensions: ^0.3.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  json_annotation: ^4.9.0
  json_diff: ^0.2.1
  json_view: ^0.4.2
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.2 

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3


flutter:
  uses-material-design: true
