include: package:very_good_analysis/analysis_options.7.0.0.yaml
linter:
  rules:
    always_put_required_named_parameters_first: false
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    no_leading_underscores_for_local_identifiers: false
    public_member_api_docs: false
