name: flow_test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.6.2

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  meta: ^1.15.0

dev_dependencies:
  very_good_analysis: ^7.0.0
